# Generated by Django 5.0.6 on 2024-08-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(choices=[('course1', 'Data Science1'), ('course2', 'Data Science2'), ('course3', 'Computer Science1'), ('course4', 'Computer Science2'), ('course5', 'Cyber Security1'), ('course6', 'Cyber Security2')], max_length=50)),
                ('Semester', models.CharField(choices=[('semester1', 'Semester 1'), ('semester2', 'Semester 2'), ('semester3', 'Semester 3'), ('semester4', 'Semester 4')], max_length=50)),
                ('Subject1', models.CharField(max_length=100)),
                ('Subject_code1', models.CharField(max_length=20)),
                ('Credits1', models.PositiveIntegerField()),
                ('Subject2', models.CharField(max_length=100)),
                ('Subject_code2', models.CharField(max_length=20)),
                ('Credits2', models.PositiveIntegerField()),
                ('Subject3', models.CharField(max_length=100)),
                ('Subject_code3', models.CharField(max_length=20)),
                ('Credits3', models.PositiveIntegerField()),
                ('Subject4', models.CharField(blank=True, max_length=100, null=True)),
                ('Subject5', models.CharField(blank=True, max_length=100, null=True)),
                ('Subject6', models.CharField(blank=True, max_length=100, null=True)),
                ('Course_description', models.TextField()),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Course_form',
                'verbose_name_plural': 'Course_forms',
            },
        ),
        migrations.CreateModel(
            name='Professor_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Contact_number', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=100)),
                ('prof_id', models.CharField(max_length=50)),
                ('Prof_username', models.CharField(max_length=50)),
                ('Prof_password', models.CharField(max_length=128)),
                ('Address', models.TextField()),
                ('Highest_degree', models.CharField(max_length=100)),
                ('Year_of_graduation', models.IntegerField()),
                ('Qualification', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
                ('Previous_position', models.CharField(max_length=100)),
                ('Previous_organization', models.CharField(max_length=100)),
                ('Current_position', models.CharField(max_length=100)),
                ('Teaching_subjects', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Professor_form',
                'verbose_name_plural': 'Professor_forms',
            },
        ),
        migrations.CreateModel(
            name='Student_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6)),
                ('Date_of_birth', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.CharField(max_length=15)),
                ('Father_name', models.CharField(max_length=100)),
                ('Occupation', models.CharField(max_length=100)),
                ('Highest_graduation', models.CharField(max_length=100)),
                ('Year_of_passout', models.CharField(max_length=4)),
                ('Specialization', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering')], max_length=50)),
                ('Percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('College_name', models.CharField(max_length=255)),
                ('College_website', models.URLField()),
                ('College_code', models.CharField(max_length=10)),
                ('IELTS_GRE_score', models.CharField(blank=True, max_length=10, null=True)),
                ('Current_course', models.CharField(choices=[('CYS', 'Cyber Security'), ('DS', 'Data Science'), ('CS', 'Computer Science')], max_length=100)),
                ('Enroll_date', models.DateField()),
                ('Course_duration', models.CharField(max_length=50)),
                ('Hall_ticket_number', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=128)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=10)),
                ('Country', models.CharField(max_length=100)),
                ('Guardian_name', models.CharField(max_length=100)),
                ('Guardian_relation', models.CharField(max_length=50)),
                ('Guardian_contact', models.CharField(max_length=15)),
                ('Guardian_email', models.EmailField(max_length=254)),
                ('Present_address', models.TextField()),
            ],
            options={
                'verbose_name': 'Student_form',
                'verbose_name_plural': 'Student_forms',
            },
        ),
    ]
