# Generated by Django 5.0.6 on 2024-08-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_ticket_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
