# Generated by Django 5.0.6 on 2024-08-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
