# Generated by Django 5.0.6 on 2024-08-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_form',
            name='Course_name',
            field=models.CharField(choices=[('Data Science1', 'Data Science1'), ('Data Science2', 'Data Science2'), ('Computer Science1', 'Computer Science1'), ('Computer Science2', 'Computer Science2'), ('Cyber Security1', 'Cyber Security1'), ('Cyber Security2', 'Cyber Security2')], max_length=50),
        ),
    ]
