# Generated by Django 5.0.6 on 2024-08-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_course_form_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_form',
            name='City',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student_form',
            name='College_code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='student_form',
            name='College_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student_form',
            name='Country',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student_form',
            name='Father_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student_form',
            name='Guardian_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student_form',
            name='Hall_ticket_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student_form',
            name='Highest_graduation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student_form',
            name='IELTS_GRE_score',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='student_form',
            name='Mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student_form',
            name='Occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_form',
            name='Password',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='student_form',
            name='Pincode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='student_form',
            name='State',
            field=models.CharField(max_length=20),
        ),
    ]
